-- Seed generato da recupero_materie_pippo.xlsx (database di riferimento fornito dall'utente)
SET search_path TO recupero_materie;

-- DB_IMPIANTI (10 righe)
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP01','FOTOVOLTAICO','SI_MONO',50,2010,2035,'Sardegna','Cagliari',39.22,9.11);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP02','FOTOVOLTAICO','SI_MONO',20,2012,2037,'Puglia','Foggia',41.46,15.55);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP03','FOTOVOLTAICO','SI_MONO',80,2015,2040,'Sicilia','Trapani',38.02,12.51);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP04','EOLICO','GB_PMSG',30,2008,2033,'Puglia','Foggia',41.46,15.55);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP05','EOLICO','GB_PMSG',45,2011,2036,'Sardegna','Nuoro',40.32,9.33);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP06','EOLICO','GB_PMSG',60,2013,2038,'Basilicata','Potenza',40.64,15.81);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP07','BESS','NMC',10,2019,2034,'Lombardia','Milano',45.46,9.19);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP08','BESS','NMC',25,2020,2035,'Piemonte','Torino',45.07,7.69);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP09','BESS','LFP',15,2021,2036,'Emilia-Romagna','Bologna',44.49,11.34);
INSERT INTO db_impianti (id_imp,tipologia,sotto_tecnologia,potenza_mw,anno_installazione,anno_dismissione,regione,provincia,lat,lon) VALUES ('IMP10','EOLICO','GB_PMSG',100,2009,2029,'Sicilia','Trapani',38.02,12.51);

-- DB_PRODOTTI (23 righe) — prima gli elementi puri
-- (elemento_confronto = se stessi), poi i composti (FK verso l'elemento)
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Ag','Argento','utile',107.87,'Ag',1,760,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Al','Alluminio','critico',26.98,'Al',1,2.3,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Co','Cobalto','strategico',58.93,'Co',1,30,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Cu','Rame','critico',63.55,'Cu',1,8.6,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Fe','Ferro','utile',55.85,'Fe',1,0.12,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Ga','Gallio','critico',69.72,'Ga',1,280,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Li','Litio','strategico',6.94,'Li',1,14,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Mn','Manganese','critico',54.94,'Mn',1,2,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Ni','Nichel','strategico',58.69,'Ni',1,17,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Pb','Piombo','utile',207.2,'Pb',1,2,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Si','Silicio','strategico',28.09,'Si',1,3,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Zn','Zinco','utile',65.38,'Zn',1,2.5,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('C','Grafite','utile',12.01,'C',1,1,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Dy','Disprosio','critico',162.5,'Dy',1,350,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Nd','Neodimio','critico',144.24,'Nd',1,80,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Pr','Praseodimio','critico',140.91,'Pr',1,95,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Tb','Terbio','critico',158.93,'Tb',1,900,0.04,0.07);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Te','Tellurio','strategico',127.6,'Te',1,75,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('MnSO4','Solfato di manganese','utile',151,'Mn',1,2.5,0.015,0.03);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('CoSO4','Solfato di Cobalto','strategico',154.99,'Co',1,12,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Li2CO3','Carbonato di Litio','strategico',73.89,'Li',2,20,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('LiOH','Idrossido di Litio','strategico',23.95,'Li',1,22,0.05,0.08);
INSERT INTO db_prodotti (prodotto,nome,categoria,peso_molare,elemento_confronto,parametro_equivalenza,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('NiSO4','Solfato di Nichel','strategico',154.75,'Ni',1,7,0.05,0.08);

-- DB_MACRO (42 righe: contenuto elementare per macrocomponente)
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_BMS','BESS','LFP','BMS_ELETTRONICA',500,'Cu',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_BMS','BESS','LFP','BMS_ELETTRONICA',500,'Fe',0.0425,0.0575);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_CABLAGGI','BESS','LFP','CABLAGGI',1000,'Cu',0.51,0.69);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_CELLE','BESS','LFP','CELLE',6000,'Fe',0.1275,0.1725);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_CELLE','BESS','LFP','CELLE',6000,'Li',0.01275,0.01725);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_INVOLUCRO','BESS','LFP','INVOLUCRO_STRUTTURA',8000,'Fe',0.34,0.46);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSL_INVOLUCRO','BESS','LFP','INVOLUCRO_STRUTTURA',8000,'Al',0.255,0.345);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_BMS','BESS','NMC','BMS_ELETTRONICA',500,'Cu',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_BMS','BESS','NMC','BMS_ELETTRONICA',500,'Fe',0.0425,0.0575);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_CABLAGGI','BESS','NMC','CABLAGGI',1000,'Cu',0.51,0.69);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_CELLE','BESS','NMC','CELLE',6000,'Mn',0.0425,0.0575);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_CELLE','BESS','NMC','CELLE',6000,'Ni',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_CELLE','BESS','NMC','CELLE',6000,'Co',0.0425,0.0575);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_CELLE','BESS','NMC','CELLE',6000,'Li',0.017,0.023);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_INVOLUCRO','BESS','NMC','INVOLUCRO_STRUTTURA',8000,'Al',0.255,0.345);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_BESSN_INVOLUCRO','BESS','NMC','INVOLUCRO_STRUTTURA',8000,'Fe',0.34,0.46);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_ARMATURE','EOLICO','GB_PMSG','ARMATURE_ACCIAIO',40000,'Fe',0.765,1);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_CABLAGGI','EOLICO','GB_PMSG','CABLAGGI',2000,'Al',0.0425,0.0575);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_CABLAGGI','EOLICO','GB_PMSG','CABLAGGI',2000,'Cu',0.51,0.69);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_GEARBOX','EOLICO','GB_PMSG','GEARBOX',6000,'Fe',0.765,1);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_GEARBOX','EOLICO','GB_PMSG','GEARBOX',6000,'Cu',0.0085,0.0115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_MAGNETI','EOLICO','GB_PMSG','MAGNETI_PERMANENTI',600,'Nd',0.0255,0.0345);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_MAGNETI','EOLICO','GB_PMSG','MAGNETI_PERMANENTI',600,'Dy',0.0085,0.0115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_MAGNETI','EOLICO','GB_PMSG','MAGNETI_PERMANENTI',600,'Pr',0.034,0.046);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_MAGNETI','EOLICO','GB_PMSG','MAGNETI_PERMANENTI',600,'Tb',0.2465,0.3335);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_PALE','EOLICO','GB_PMSG','PALE',8000,'Fe',0.017,0.023);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI',500,'Al',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI',500,'Cu',0.17,0.23);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI',500,'Fe',0.255,0.345);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_EOL_STRUTTURA','EOLICO','GB_PMSG','STRUTTURA_ACCIAIO',50000,'Fe',0.8075,1);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_CABLAGGI','FOTOVOLTAICO','SI_MONO','CABLAGGI',2000,'Cu',0.595,0.805);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER',3000,'Fe',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER',3000,'Al',0.17,0.23);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER',3000,'Cu',0.1275,0.1725);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_MODULI','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI',60000,'Cu',0.0085,0.0115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_MODULI','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI',60000,'Ag',0.00043,0.00058);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_MODULI','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI',60000,'Al',0.085,0.115);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_MODULI','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI',60000,'Si',0.034,0.046);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_QUADRI','FOTOVOLTAICO','SI_MONO','QUADRI_ELETTRICI',500,'Fe',0.255,0.345);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_QUADRI','FOTOVOLTAICO','SI_MONO','QUADRI_ELETTRICI',500,'Cu',0.17,0.23);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_STRUTTURA','FOTOVOLTAICO','SI_MONO','STRUTTURA_MONTAGGIO',25000,'Al',0.34,0.46);
INSERT INTO db_macro (id_macro,tipologia,sotto_tecnologia,macro_componente,massa_kg_per_mw,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('M_PV_STRUTTURA','FOTOVOLTAICO','SI_MONO','STRUTTURA_MONTAGGIO',25000,'Fe',0.425,0.575);

-- DB_INTERMEDI (4 righe)
INSERT INTO db_intermedi (intermedio,nome,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('BM','Black Mass',5.5,0.03,0.05);
INSERT INTO db_intermedi (intermedio,nome,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('MHP','Idrossido misto Ni-Co (MHP)',8,0.04,0.07);
INSERT INTO db_intermedi (intermedio,nome,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('cake_metallico','cake_metallico',5,0.04,0.07);
INSERT INTO db_intermedi (intermedio,nome,prezzo_attuale_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2) VALUES ('Elet','Elettrolita',1,0.015,0.03);

-- DB_MACRO_PROCESSI (28 righe)
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSL_BMS','BESS','LFP','BMS_ELETTRONICA','SMONTAGGIO',9,250,1,0.02,0.035,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSL_CABLAGGI','BESS','LFP','CABLAGGI','SMONTAGGIO',9,250,3.5,0.03,0.05,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSL_CELLE','BESS','LFP','CELLE','SMONTAGGIO_MODULI',9,250,1,0.02,0.035,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSL_INVOLUCRO','BESS','LFP','INVOLUCRO_STRUTTURA','SMONTAGGIO',9,250,0.5,0.015,0.025,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSN_BMS','BESS','NMC','BMS_ELETTRONICA','SMONTAGGIO',9,250,1,0.02,0.035,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSN_CABLAGGI','BESS','NMC','CABLAGGI','SMONTAGGIO',9,250,3.5,0.03,0.05,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSN_CELLE','BESS','NMC','CELLE','SMONTAGGIO_MODULI',9,250,2.5,0.03,0.05,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_BESSN_INVOLUCRO','BESS','NMC','INVOLUCRO_STRUTTURA','SMONTAGGIO',9,250,0.5,0.015,0.025,'scarica_profonda, Smontaggio_manuale');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_ARMATURE','EOLICO','GB_PMSG','ARMATURE_ACCIAIO','SMONTAGGIO_E_TRASPORTO',45,90,0.18,0.015,0.025,'DEMOLIZIONE_FONDAZIONE, ESTRAZIONE_ARMATURE, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_ARMATURE_SD','EOLICO','GB_PMSG','ARMATURE_ACCIAIO','SOLO_DISASSEMBLAGGIO',33,59,0.18,0.015,0.025,'DEMOLIZIONE_FONDAZIONE, ESTRAZIONE_ARMATURE');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_CABLAGGI','EOLICO','GB_PMSG','CABLAGGI','SMONTAGGIO_E_TRASPORTO',20,40,3.5,0.03,0.05,'SEZIONAMENTO_ELETTRICO, ESTRAZIONE_CAVI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_CABLAGGI_SD','EOLICO','GB_PMSG','CABLAGGI','SOLO_DISASSEMBLAGGIO',15,26,3.5,0.03,0.05,'SEZIONAMENTO_ELETTRICO, ESTRAZIONE_CAVI');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_GEARBOX','EOLICO','GB_PMSG','GEARBOX','SMONTAGGIO_E_TRASPORTO',40,80,0.25,0.015,0.025,'APERTURA_NAVICELLA, SGANCIO_GEARBOX, CALATA_A_TERRA, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_GEARBOX_SD','EOLICO','GB_PMSG','GEARBOX','SOLO_DISASSEMBLAGGIO',30,50,0.25,0.015,0.025,'APERTURA_NAVICELLA, SGANCIO_GEARBOX, CALATA_A_TERRA');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_MAGNETI','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','SMONTAGGIO_E_TRASPORTO',60,120,8,0.04,0.07,'APERTURA_GENERATORE, ESTRAZIONE_ROTORE, SEPARAZIONE_MAGNETI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_MAGNETI_SD','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','SOLO_DISASSEMBLAGGIO',45,75,8,0.04,0.07,'APERTURA_GENERATORE, ESTRAZIONE_ROTORE, SEPARAZIONE_MAGNETI');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_PALE','EOLICO','GB_PMSG','PALE','RIMOZIONE_E_TRASPORTO',30,60,0.02,0.01,0.02,'RIMOZIONE_PALA, TRASPORTO_A_TERRA, STOCCAGGIO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_PALE_SD','EOLICO','GB_PMSG','PALE','SOLO_DISASSEMBLAGGIO',22,36,0.02,0.01,0.02,'RIMOZIONE_PALA, STOCCAGGIO_IN_SITO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_PALE_TAGLIO','EOLICO','GB_PMSG','PALE','TAGLIO_IN_SITO',45,70,0.015,0.01,0.02,'TAGLIO_PALA_IN_SITO, FRANTUMAZIONE_SEGMENTI, STOCCAGGIO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI','SMONTAGGIO_E_TRASPORTO',25,50,1.2,0.02,0.035,'SEZIONAMENTO_ELETTRICO, RIMOZIONE_QUADRI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_QUADRI_SD','EOLICO','GB_PMSG','QUADRI_ELETTRICI','SOLO_DISASSEMBLAGGIO',18,33,1.2,0.02,0.035,'SEZIONAMENTO_ELETTRICO, RIMOZIONE_QUADRI');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_STRUTTURA','EOLICO','GB_PMSG','STRUTTURA_ACCIAIO','SMONTAGGIO_E_TRASPORTO',35,70,0.22,0.015,0.025,'ABBATTIMENTO_TORRE, SEZIONAMENTO_TRONCONI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_EOL_STRUTTURA_SD','EOLICO','GB_PMSG','STRUTTURA_ACCIAIO','SOLO_DISASSEMBLAGGIO',26,46,0.22,0.015,0.025,'ABBATTIMENTO_TORRE, SEZIONAMENTO_TRONCONI');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_PV_CABLAGGI','FOTOVOLTAICO','SI_MONO','CABLAGGI','SMONTAGGIO_E_TRASPORTO',15,25,3.5,0.03,0.05,'SEZIONAMENTO_ELETTRICO, ESTRAZIONE_CAVI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER','SMONTAGGIO_E_TRASPORTO',20,35,1,0.02,0.035,'SEZIONAMENTO_ELETTRICO, RIMOZIONE_INVERTER, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_PV_MODULI','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','SMONTAGGIO_E_TRASPORTO',15,30,0.08,0.015,0.03,'SCOLLEGAMENTO_STRINGHE, RIMOZIONE_MODULI, IMBALLAGGIO, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_PV_QUADRI','FOTOVOLTAICO','SI_MONO','QUADRI_ELETTRICI','SMONTAGGIO_E_TRASPORTO',20,35,1.2,0.02,0.035,'SEZIONAMENTO_ELETTRICO, RIMOZIONE_QUADRI, TRASPORTO');
INSERT INTO db_macro_processi (id_processo_macro,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,prezzo_vendita_eur_kg,proiezione_prezzo_p1,proiezione_prezzo_p2,descrizione_fasi) VALUES ('MP_PV_STRUTTURA','FOTOVOLTAICO','SI_MONO','STRUTTURA_MONTAGGIO','SMONTAGGIO_E_TRASPORTO',25,45,0.6,0.02,0.03,'SVITATURA_STAFFE, RIMOZIONE_STRUTTURA, TRASPORTO');

-- DB_PROCESSI (64 righe)
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_PALE','EOLICO','GB_PMSG','PALE','TRITURAZIONE_MECCANICA',50,100,'prodotto','Fe',NULL,0.651,0.735,'TRITURAZIONE, VAGLIATURA, SEPARAZIONE_MAGNETICA_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_GEARBOX','EOLICO','GB_PMSG','GEARBOX','SMONTAGGIO_RECUPERO_METALLICO',150,300,'prodotto','Fe',NULL,0.8556,0.966,'SMONTAGGIO, DRENAGGIO_OLIO, FRANTUMAZIONE, SEPARAZIONE_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_GEARBOX','EOLICO','GB_PMSG','GEARBOX','SMONTAGGIO_RECUPERO_METALLICO',150,300,'prodotto','Cu',NULL,0.7905,0.8925,'SMONTAGGIO, DRENAGGIO_OLIO, FRANTUMAZIONE, SEPARAZIONE_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_DIRETTO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','RICICLO_DIRETTO',1200,15000,'prodotto','Nd',NULL,0.8835,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, ROTTURA_CON_IDROGENO, MACINAZIONE, PRESSATURA_IN_CAMPO_MAGNETICO, SINTERIZZAZIONE, TRATTAMENTO_TERMICO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_DIRETTO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','RICICLO_DIRETTO',1200,15000,'prodotto','Dy',NULL,0.8928,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, ROTTURA_CON_IDROGENO, MACINAZIONE, PRESSATURA_IN_CAMPO_MAGNETICO, SINTERIZZAZIONE, TRATTAMENTO_TERMICO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_DIRETTO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','RICICLO_DIRETTO',1200,15000,'prodotto','Pr',NULL,0.8835,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, ROTTURA_CON_IDROGENO, MACINAZIONE, PRESSATURA_IN_CAMPO_MAGNETICO, SINTERIZZAZIONE, TRATTAMENTO_TERMICO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_DIRETTO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','RICICLO_DIRETTO',1200,15000,'prodotto','Tb',NULL,0.8835,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, ROTTURA_CON_IDROGENO, MACINAZIONE, PRESSATURA_IN_CAMPO_MAGNETICO, SINTERIZZAZIONE, TRATTAMENTO_TERMICO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_IDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','IDROMETALLURGIA',2000,30000,'prodotto','Nd',NULL,0.837,0.945,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_IDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','IDROMETALLURGIA',2000,30000,'prodotto','Dy',NULL,0.9114,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_IDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','IDROMETALLURGIA',2000,30000,'prodotto','Pr',NULL,0.837,0.945,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_IDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','IDROMETALLURGIA',2000,30000,'prodotto','Tb',NULL,0.837,0.945,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA',1500,20000,'prodotto','Nd',NULL,0.744,0.84,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, FUSIONE_ARROSTIMENTO, RAFFINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA',1500,20000,'prodotto','Dy',NULL,0.8835,0.99,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, FUSIONE_ARROSTIMENTO, RAFFINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA',1500,20000,'prodotto','Pr',NULL,0.744,0.84,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, FUSIONE_ARROSTIMENTO, RAFFINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA',1500,20000,'prodotto','Tb',NULL,0.744,0.84,'SMONTAGGIO, DEMAGNETIZZAZIONE, FRANTUMAZIONE, FUSIONE_ARROSTIMENTO, RAFFINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIROIDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA_E_IDROMETALLURGIA',2500,35000,'prodotto','Nd',NULL,0.837,0.945,'SMONTAGGIO, ARROSTIMENTO, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIROIDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA_E_IDROMETALLURGIA',2500,35000,'prodotto','Dy',NULL,0.9114,0.99,'SMONTAGGIO, ARROSTIMENTO, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIROIDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA_E_IDROMETALLURGIA',2500,35000,'prodotto','Pr',NULL,0.837,0.945,'SMONTAGGIO, ARROSTIMENTO, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_MAGNETI_PIROIDRO','EOLICO','GB_PMSG','MAGNETI_PERMANENTI','PIROMETALLURGIA_E_IDROMETALLURGIA',2500,35000,'prodotto','Tb',NULL,0.837,0.945,'SMONTAGGIO, ARROSTIMENTO, FRANTUMAZIONE, MACINAZIONE, LISCIVIAZIONE_ACIDA, SEPARAZIONE_SOLIDO_LIQUIDO, ESTRAZIONE_CON_SOLVENTE, PRECIPITAZIONE_REE, FILTRAZIONE_PRECIPITATO, CALCINAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_CABLAGGI','EOLICO','GB_PMSG','CABLAGGI','SPELLATURA_RECUPERO_RAME',80,150,'prodotto','Cu',NULL,0.8835,0.99,'SPELLATURA_GUAINE, GRANULAZIONE, SEPARAZIONE_DENSIMETRICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_CABLAGGI','EOLICO','GB_PMSG','CABLAGGI','SPELLATURA_RECUPERO_RAME',80,150,'prodotto','Al',NULL,0.7905,0.8925,'SPELLATURA_GUAINE, GRANULAZIONE, SEPARAZIONE_DENSIMETRICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI','SMONTAGGIO_COMPONENTI_ELETTRONICI',200,400,'prodotto','Cu',NULL,0.837,0.945,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI','SMONTAGGIO_COMPONENTI_ELETTRONICI',200,400,'prodotto','Fe',NULL,0.7905,0.8925,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_QUADRI','EOLICO','GB_PMSG','QUADRI_ELETTRICI','SMONTAGGIO_COMPONENTI_ELETTRONICI',200,400,'prodotto','Al',NULL,0.744,0.84,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_STRUTTURA','EOLICO','GB_PMSG','STRUTTURA_ACCIAIO','FRANTUMAZIONE_RECUPERO_ACCIAIO',50,100,'prodotto','Fe',NULL,0.8928,0.99,'TAGLIO, FRANTUMAZIONE, SEPARAZIONE_MAGNETICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_EOL_ARMATURE','EOLICO','GB_PMSG','ARMATURE_ACCIAIO','FRANTUMAZIONE_RECUPERO_ACCIAIO',50,100,'prodotto','Fe',NULL,0.8742,0.987,'DEMOLIZIONE, FRANTUMAZIONE, SEPARAZIONE_MAGNETICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_MECC','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_MECCANICO',150,250,'prodotto','Si',NULL,0.558,0.63,'SMONTAGGIO_TELAIO, FRANTUMAZIONE, VAGLIATURA, SEPARAZIONE_MATERIALI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_MECC','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_MECCANICO',150,250,'prodotto','Al',NULL,0.8835,0.99,'SMONTAGGIO_TELAIO, FRANTUMAZIONE, VAGLIATURA, SEPARAZIONE_MATERIALI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_MECC','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_MECCANICO',150,250,'prodotto','Ag',NULL,0.465,0.525,'SMONTAGGIO_TELAIO, FRANTUMAZIONE, VAGLIATURA, SEPARAZIONE_MATERIALI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_MECC','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_MECCANICO',150,250,'prodotto','Cu',NULL,0.651,0.735,'SMONTAGGIO_TELAIO, FRANTUMAZIONE, VAGLIATURA, SEPARAZIONE_MATERIALI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_TERMOCHIM','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_TERMICO_CHIMICO',400,600,'prodotto','Si',NULL,0.837,0.945,'DELAMINAZIONE_TERMICA, LISCIVIAZIONE_ACIDA, RECUPERO_METALLI, PURIFICAZIONE_SILICIO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_TERMOCHIM','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_TERMICO_CHIMICO',400,600,'prodotto','Al',NULL,0.8928,0.99,'DELAMINAZIONE_TERMICA, LISCIVIAZIONE_ACIDA, RECUPERO_METALLI, PURIFICAZIONE_SILICIO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_TERMOCHIM','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_TERMICO_CHIMICO',400,600,'prodotto','Ag',NULL,0.8556,0.966,'DELAMINAZIONE_TERMICA, LISCIVIAZIONE_ACIDA, RECUPERO_METALLI, PURIFICAZIONE_SILICIO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_MODULI_TERMOCHIM','FOTOVOLTAICO','SI_MONO','MODULI_FOTOVOLTAICI','RICICLO_TERMICO_CHIMICO',400,600,'prodotto','Cu',NULL,0.7905,0.8925,'DELAMINAZIONE_TERMICA, LISCIVIAZIONE_ACIDA, RECUPERO_METALLI, PURIFICAZIONE_SILICIO');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER','SMONTAGGIO_ELETTRONICO',200,350,'prodotto','Cu',NULL,0.8184,0.924,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER','SMONTAGGIO_ELETTRONICO',200,350,'prodotto','Al',NULL,0.837,0.945,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_INVERTER','FOTOVOLTAICO','SI_MONO','INVERTER','SMONTAGGIO_ELETTRONICO',200,350,'prodotto','Fe',NULL,0.7905,0.8925,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_STRUTTURA','FOTOVOLTAICO','SI_MONO','STRUTTURA_MONTAGGIO','FRANTUMAZIONE_METALLI',60,100,'prodotto','Al',NULL,0.8835,0.99,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_STRUTTURA','FOTOVOLTAICO','SI_MONO','STRUTTURA_MONTAGGIO','FRANTUMAZIONE_METALLI',60,100,'prodotto','Fe',NULL,0.8556,0.966,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_CABLAGGI','FOTOVOLTAICO','SI_MONO','CABLAGGI','SPELLATURA_RECUPERO_RAME',80,150,'prodotto','Cu',NULL,0.8835,0.99,'SPELLATURA_GUAINE, GRANULAZIONE, SEPARAZIONE_DENSIMETRICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_QUADRI','FOTOVOLTAICO','SI_MONO','QUADRI_ELETTRICI','SMONTAGGIO_COMPONENTI_ELETTRONICI',200,400,'prodotto','Cu',NULL,0.837,0.945,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_PV_QUADRI','FOTOVOLTAICO','SI_MONO','QUADRI_ELETTRICI','SMONTAGGIO_COMPONENTI_ELETTRONICI',200,400,'prodotto','Fe',NULL,0.7905,0.8925,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P1','BESS','NMC','CELLE','NMC_P1_IDROM_solomeccanico',112.5,325,'intermedio',NULL,'BM',0.23,0.26,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, ESTRAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P1','BESS','NMC','CELLE','NMC_P1_IDROM_solomeccanico',112.5,325,'prodotto','Cu',NULL,0.227,0.247,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, ESTRAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P1','BESS','NMC','CELLE','NMC_P1_IDROM_solomeccanico',112.5,325,'prodotto','Al',NULL,0.057,0.077,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, ESTRAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P1','BESS','NMC','CELLE','NMC_P1_IDROM_solomeccanico',112.5,325,'intermedio',NULL,'Elet',0.155,0.175,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, ESTRAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P2','BESS','NMC','CELLE','NMC_P2_IDROM_Mecc&Refiner_completo',1062.5,1790,'prodotto','C',NULL,0.098,0.11800000000000001,'TRITURAZIONE,SEPARAZIONE, LISCIVIAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P2','BESS','NMC','CELLE','NMC_P2_IDROM_Mecc&Refiner_completo',1062.5,1790,'prodotto','CoSO4',NULL,0.48,0.5,'TRITURAZIONE,SEPARAZIONE, LISCIVIAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P2','BESS','NMC','CELLE','NMC_P2_IDROM_Mecc&Refiner_completo',1062.5,1790,'prodotto','NiSO4',NULL,0.48,0.5,'TRITURAZIONE,SEPARAZIONE, LISCIVIAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P2','BESS','NMC','CELLE','NMC_P2_IDROM_Mecc&Refiner_completo',1062.5,1790,'prodotto','MnSO4',NULL,0.385,0.405,'TRITURAZIONE,SEPARAZIONE, LISCIVIAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P2','BESS','NMC','CELLE','NMC_P2_IDROM_Mecc&Refiner_completo',1062.5,1790,'prodotto','LiOH',NULL,0.19,0.21,'TRITURAZIONE,SEPARAZIONE, LISCIVIAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_BMS','BESS','NMC','BMS_ELETTRONICA','SMONTAGGIO_ELETTRONICO',250,500,'prodotto','Cu',NULL,0.7905,0.8925,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_BMS','BESS','NMC','BMS_ELETTRONICA','SMONTAGGIO_ELETTRONICO',250,500,'prodotto','Fe',NULL,0.744,0.84,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_INVOLUCRO','BESS','NMC','INVOLUCRO_STRUTTURA','FRANTUMAZIONE_METALLI',60,100,'prodotto','Al',NULL,0.8649,0.9765,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_INVOLUCRO','BESS','NMC','INVOLUCRO_STRUTTURA','FRANTUMAZIONE_METALLI',60,100,'prodotto','Fe',NULL,0.837,0.945,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CABLAGGI','BESS','NMC','CABLAGGI','SPELLATURA_RECUPERO_RAME',80,150,'prodotto','Cu',NULL,0.8835,0.99,'SPELLATURA_GUAINE, GRANULAZIONE, SEPARAZIONE_DENSIMETRICA');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_CELLE_DIRETTO','BESS','LFP','CELLE','IDROMETALLURGIA_LFP',2500,20000,'prodotto','Li',NULL,0.744,0.84,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_CELLE_DIRETTO','BESS','LFP','CELLE','IDROMETALLURGIA_LFP',2500,20000,'prodotto','Fe',NULL,0.837,0.945,'SCARICA, SMONTAGGIO, FRANTUMAZIONE, LISCIVIAZIONE_ACIDA, PRECIPITAZIONE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_CELLE_BLACKMASS','BESS','LFP','CELLE','PIROLISI_E_TRITURAZIONE',1600,14000,'intermedio',NULL,'BM',0.4185,0.4725,'SCARICA_SICUREZZA, PIROLISI, TRITURAZIONE, VAGLIATURA_BM');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_BMS','BESS','LFP','BMS_ELETTRONICA','SMONTAGGIO_ELETTRONICO',250,500,'prodotto','Cu',NULL,0.7905,0.8925,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_BMS','BESS','LFP','BMS_ELETTRONICA','SMONTAGGIO_ELETTRONICO',250,500,'prodotto','Fe',NULL,0.744,0.84,'SMONTAGGIO, SEPARAZIONE_SCHEDE, RECUPERO_METALLI');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_INVOLUCRO','BESS','LFP','INVOLUCRO_STRUTTURA','FRANTUMAZIONE_METALLI',60,100,'prodotto','Al',NULL,0.8649,0.9765,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_INVOLUCRO','BESS','LFP','INVOLUCRO_STRUTTURA','FRANTUMAZIONE_METALLI',60,100,'prodotto','Fe',NULL,0.837,0.945,'SMONTAGGIO, TAGLIO, SEPARAZIONE_LEGHE');
INSERT INTO db_processi (id_processo,tipologia,sotto_tecnologia,macro_componente,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSL_CABLAGGI','BESS','LFP','CABLAGGI','SPELLATURA_RECUPERO_RAME',80,150,'prodotto','Cu',NULL,0.8835,0.99,'SPELLATURA_GUAINE, GRANULAZIONE, SEPARAZIONE_DENSIMETRICA');

-- DB_SOTTOPROCESSI (12 righe) — input normalizzato su BM (era BLACK_MASS nel file
-- originale); rese di CoSO4/NiSO4/MnSO4/LiOH/MHP/cake_metallico sostituite (vedi commento sopra)
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P3','BM','NMC_P3_IDROM_Refiner completo',2500,2000,'prodotto','CoSO4',NULL,0.88,0.92,' LISCIVIAZIONE, PURIFICAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P3','BM','NMC_P3_IDROM_Refiner completo',2500,2000,'prodotto','NiSO4',NULL,0.88,0.92,' LISCIVIAZIONE, PURIFICAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P3','BM','NMC_P3_IDROM_Refiner completo',2500,2000,'prodotto','MnSO4',NULL,0.82,0.88,' LISCIVIAZIONE, PURIFICAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P3','BM','NMC_P3_IDROM_Refiner completo',2500,2000,'prodotto','LiOH',NULL,0.85,0.9,' LISCIVIAZIONE, PURIFICAZIONE, SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P4','BM','NMC_P4_IDROM_MHP',1438,1550,'intermedio',NULL,'MHP',0.4,0.45,' LISCIVIAZIONE, PURIFICAZIONE,  PRECIPITAZIONE_MISTA');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P4','BM','NMC_P4_IDROM_MHP',1438,1550,'prodotto','Li2CO3',NULL,0.78,0.85,' LISCIVIAZIONE, PURIFICAZIONE,  PRECIPITAZIONE_MISTA');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P5','BM','NMC_P5_IDROM_Li',1250,1253,'prodotto','Li2CO3',NULL,0.8,0.86,' LISCIVIAZIONE, PURIFICAZIONE,  PRECIPITAZIONE_MISTA');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P5','BM','NMC_P5_IDROM_Li',1250,1253,'intermedio',NULL,'cake_metallico',0.55,0.6,' LISCIVIAZIONE, PURIFICAZIONE,  PRECIPITAZIONE_MISTA');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P6','MHP','NMC_P6_IDROM_Raffineria',1250,1100,'prodotto','CoSO4',NULL,0.9,0.94,' SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P6','MHP','NMC_P6_IDROM_Raffineria',1250,1100,'prodotto','NiSO4',NULL,0.9,0.94,' SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P6','MHP','NMC_P6_IDROM_Raffineria',1250,1100,'prodotto','MnSO4',NULL,0.85,0.9,' SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');
INSERT INTO db_sottoprocessi (id_sottoprocesso,intermedio,tecnica,capex_eur_ton,opex_eur_ton,tipo_output,prodotto,intermedio_output,recupero_pct_min,recupero_pct_max,descrizione_fasi) VALUES ('P_BESSN_CELLE_P6','MHP','NMC_P6_IDROM_Raffineria',1250,1100,'prodotto','LiOH',NULL,0.85,0.9,' SEPARAZIONE_SOLVENTE, PRECIPITAZIONE');

-- DB_INTERMEDI_COMPOSIZIONE (8 righe) — non presente nel file originale,
-- aggiunta perche' la stechiometria valga sempre anche a partire da un intermedio
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('BM','Co',0.12,0.16);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('BM','Ni',0.28,0.32);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('BM','Mn',0.1,0.14);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('BM','Li',0.05,0.07);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('MHP','Co',0.2,0.24);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('MHP','Ni',0.42,0.46);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('MHP','Mn',0.03,0.05);
INSERT INTO db_intermedi_composizione (intermedio,prodotto,pct_contenuto_min,pct_contenuto_max) VALUES ('MHP','Li',0.01,0.02);

-- DB_INDICI_RIVALUTAZIONE (3 righe)
INSERT INTO db_indici_rivalutazione VALUES ('EDILIZIA','Indice costi di costruzione',0.03);
INSERT INTO db_indici_rivalutazione VALUES ('ISTAT','Indice ISTAT prezzi al consumo (FOI)',0.02);
INSERT INTO db_indici_rivalutazione VALUES ('NESSUNA','Nessuna rivalutazione (costi costanti)',0);
